Combine the gecko perfstats from each process
sitespeedio/browsertime pull request #1504
Opened 2021-03-12 20:59 UTC by acreskeyMoz

The perfstats are collected for each process.

In this PR I accumulate the timings in such a structure:

```
"geckoPerfStats": [
      {
        "DisplayList Building": 61,
        "Rasterizing": 255,
        "LayerBuilding": 27,
        "Layer Transactions": 70,
        "Compositing": 2014,
        "Reflowing": 52,
        "Styling": 78,
        "HttpChannelCompletion_Network": 279599,
        "HttpChannelCompletion_Cache": 705
      }
    ],
    ```

2021-03-12 20:59 UTC, acreskeyMoz commented
(I'm really a novice JS programmer, so please let me know if anything could be improved!)

2021-03-14 19:49 UTC, soulgalore commented on lib/firefox/perfStats.js
> +      let combinedPerfStats = {};
I would just make this `const` since it is never reassigned.

2021-03-14 19:49 UTC, soulgalore commented on lib/firefox/perfStats.js
> +      let perfStats = JSON.parse(perfStatsResult);
Const here too!

2021-03-14 19:50 UTC, soulgalore requested changes
Small nitty pick, make them const. As long as a variable isn't reassiged, always make em const. If you gonna re-assign then, then make em let.

2021-03-14 19:54 UTC, soulgalore commented
Hi @acreskeyMoz cool! This looks fine, I just added two small things about when to make const instead of let. And no worries, I can also just change them afterwards, if people don't ask about feedback I usual just merge and then change, I'm not picky about the code for PRs as long as they work :)

2021-03-15 11:13 UTC, acreskeyMoz commented
> Small nitty pick, make them const. As long as a variable isn't reassiged, always make em const. If you gonna re-assign then, then make em let.

Thanks @soulgalore -- I was looking for feedback to improve my JS as well :)
Fixed!

2021-03-15 12:15 UTC, merged