Add debug
sitespeedio/browsertime pull request #1798
Opened 2022-05-29 07:22 UTC by soulgalore

@gmierz I think this is ok now from my side, do you think it will work for you?

See also #1790

2022-06-02 15:46 UTC, gmierz requested changes
This looks great @soulgalore! :)

I tested it out locally and the only thing that's missing here is to not close the browser in debug mode. Otherwise, the browser gets closed even if it's in detached mode.

2022-06-02 19:35 UTC, soulgalore commented on lib/support/cli.js
> +      describe: 'Run the Browsertime in debug mode.',
You are right, I don't know where I got that from.

2022-06-02 19:39 UTC, soulgalore commented
> I tested it out locally and the only thing that's missing here is to not close the browser in debug mode. Otherwise, the browser gets closed even if it's in detached mode.

Ah I missed that. I'll add that for Firefox!

2022-06-03 06:58 UTC, merged

2022-06-03 13:00 UTC, gmierz commented
Thank you so much for taking care of this @soulgalore! :)